admin_tools/urls.py
from admin_tools import views, run_startup
from django.urls import path

# In order to call to those as `admin_tools:view_name` we need this
app_name = "admin_tools"

urlpatterns = [
    path("", views.index, name="index"),
    path(
        "import_yaml",
        views.import_lockable_resources_from_yaml,
        name="import_lockable_resources_from_yaml",
    ),
    path(
        "manage_addons",
        views.manage_addons,
        name="manage_addons",
    ),
]


# Use this section to call to a code that runs one time once the application loads:
run_startup.main()

api/urls.py
from django.urls import path
from api import views

urlpatterns = [
    path("", views.redirect_to_prior_location, name="redirect_to_prior_location"),
    path("resources/", views.resources_view, name="resources_view"),
    path(
        "resource/retrieve_entrypoint/<search_string>",
        views.retrieve_resource_entrypoint,
        name="retrieve_resource_entrypoint",
    ),
    # Example from web browser UI:
    # http://127.0.0.1:8000/api/resource/retrieve_name/aws-resource-3%3Fpriority=1%3Fsignoff=cerginba-cluster66666
    path(
        "resource/retrieve_name/<name>?priority=<priority>?signoff=<signoff>?link=<link>",
        views.retrieve_resource_by_name,
        name="retrieve_resource_by_name",
    ),
    path(
        "resource/retrieve_label/<label>?priority=<priority>?signoff=<signoff>?link=<link>",
        views.retrieve_resource_by_label,
        name="retrieve_resource_by_label",
    ),
    path("resource/<slug>", views.resource_view, name="resource_view"),
    path("rqueue/<slug>", views.rqueue_view, name="rqueue_view"),
    path("rqueues", views.rqueues_view, name="rqueues_view"),
    path(
        "pendingrequests",
        views.rqueues_status_pending_view,
        name="rqueues_status_pending_view",
    ),
    path(
        "present_requests",
        views.rqueues_status_present_view,
        name="rqueues_status_present_view",
    ),
]

lockable_resource/urls.py
from lockable_resource import views
from django.urls import path

urlpatterns = [
    path("", views.lockable_resources_page, name="lockable_resources_page"),
    path(
        "<slug>/", views.lockable_resource_more_info, name="lockable_resource_more_info"
    ),
]

rlocker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("lockable_resource/", include("lockable_resource.urls")),
    path("api/", include("api.urls")),
    path("", include("account.urls")),
    path("", include("rqueue.urls")),
    path("", include("dashboard.urls")),
    path("", include("health.urls")),
    path("admin_tools/", include("admin_tools.urls")),
    path("patch_notifier/", include("patch_notifier.urls")),
    path("patch_notifier/", include("patch_notifier.urls")),
    path('resoucesdc/', include('resoucesdc.urls')),
]
# AddOns Urls
for addon in settings.INSTALLED_ADDONS:
    urlpatterns.append(path(f"{addon}/", include(f"{addon}.urls")))

lockable_resource/models.py
from django.db import models
from lockable_resource.exceptions import AlreadyFreeException, AlreadyLockedException
from rqueue.models import Rqueue
from rqueue.utils import DescriptiveTime
import lockable_resource.constants as const
import json
import yaml
from django.utils.timezone import utc
import datetime


class LockableResource(models.Model):
    # Fields:
    # id - Primary key to identify each lockable resource obj. (Auto Generated)
    # provider - The Cloud provider.
    # name - Name of the resource.
    # is_locked - Status of the lockable resource described by
    #    if locked or not, default is False. New created Lockable
    #       resource should be released.
    # labels - All the labels a lockable resource can have.
    # signoff - To be aware who locked the resource, we want to have a signoff
    #               that will describe who was in charge to change the status of it.
    # TODO: signoff should support HTML so it will be easier to send Jenkins Job Links
    # description - We want to have some random text to describe lockable resource
    # in_maintenance - Describes whether if the resource is in maintenance or not, we will disable
    # associated_queue - The queue object that locked the resource
    # all functionalities to lock/release resource is it is.
    # locked_time - The time that identifies when the last time resource is locked
    provider = models.CharField(max_length=256)
    name = models.CharField(max_length=256, unique=True)
    is_locked = models.BooleanField(default=False)
    labels_string = models.CharField(max_length=2048)
    signoff = models.CharField(
        max_length=2048, null=True, default=None, blank=True, unique=True
    )
    cpu = models.IntegerField(default=0)
    memory = models.IntegerField(default=0)
    storage = models.IntegerField(default=0)
    description = models.CharField(max_length=2048, null=True, default=None, blank=True)
    link = models.CharField(max_length=2048, null=True, default=None, blank=True)
    in_maintenance = models.BooleanField(default=False)
    associated_queue = models.OneToOneField(
        Rqueue,
        default=None,
        blank=True,
        null=True,
        on_delete=models.PROTECT,
        to_field="id",
    )
    locked_time = models.DateTimeField(null=True, default=None, blank=True)

    @property
    def labels(self):
        """
        Instance Property
        Since the labels are stored as white-space separated in DB,
            this property is to receive the labels as a list
        :returns: List of all the labels
        """
        return self.labels_string.split()

    @property
    def free_and_not_in_maintenance(self):
        """
        Instance Property
        Returns if the lockable resource could be locked at all.
             - Resource could be locked
             - Resource could be under maintenance


        :return: Bool True/False
        """
        return not self.is_locked and not self.in_maintenance

    @property
    def status_properties(self):
        """
        Instance Property
        Includes additional key&values about the status of the LockableResource obj
        Depending on the status, we want to include different styling for the HTML template

        :returns: Dictionary:
            `status` : Status of the LR, locked or not
            `color`  : Color to describe the situation (Green or Red)
            `icon`  : Icon to describe the situation from Bootstrap Classes
        """
        if self.is_locked:
            # For safety, we check that the locked period is not none before retrieving the total seconds
            locked_time_description = ""
            if self.locked_period:
                locked_time_description = DescriptiveTime(
                    self.locked_period.total_seconds()
                ).short_descriptive
            return {
                "status": const.STATUS_LOCKED,
                "color": "#D6212E",
                "icon": "icon_lock",
                "more_info": locked_time_description,
            }
        elif self.in_maintenance:
            return {
                "status": const.STATUS_MAINTENANCE,
                "color": "#FFA500",
                "icon": "icon_lock",
                "more_info": "",
            }
        else:
            return {
                "status": const.STATUS_FREE,
                "color": "#00C100",
                "icon": "icon_lock-open",
                "more_info": "",
            }

    @property
    def can_lock(self):
        """
        Instance Property
        :returns Boolean:
        """
        return not self.is_locked

    @property
    def can_release(self):
        """
        Instance Property
        :returns Boolean:
        """
        return self.is_locked

    @property
    def locked_period(self):
        """
        Instance Property
        This property added way after the application initialized.
        So it is required to check if the field is not none,
            before returning the timediff
        :returns timedelta: The kind of object when subtracting datetime objects
        """
        if self.locked_time:
            now = datetime.datetime.utcnow().replace(tzinfo=utc)
            timediff = now - self.locked_time
            return timediff

    @property
    def locked_period_descriptive(self):
        """
        Instance Property
        :returns str: Descriptive time of the time object
        """
        if self.locked_period:
            return DescriptiveTime(self.locked_period.total_seconds()).long_descriptive

    def next_obj(self):
        """
        Instance method
        Added in order to get the next object
        Return the first object in the list if last is reached

        """
        next_object = (
            LockableResource.objects.filter(pk__gt=self.pk).order_by("pk").first()
        )  # Do not use the variable name next, it's a built in keyword
        if next_object:
            return next_object
        else:
            return LockableResource.objects.all().order_by("pk").first()

    def previous_obj(self):
        """
        Instance method
        Added in order to get the previous object
        Return the first object in the list if last is reached

        """
        previous = (
            LockableResource.objects.filter(pk__lt=self.pk).order_by("-pk").first()
        )
        if previous:
            return previous
        else:
            return LockableResource.objects.all().order_by("-pk").first()

    @property
    def lock_method(self):
        """
        Return the method string of the way how resource
            has been locked
        :return str:
        """
        if self.associated_queue:
            return (
                const.LockMethod.AUTO
                if self.associated_queue.priority > 0
                else const.LockMethod.MANUAL
            )

    def lock(self, signoff):
        """
        Instance Method

        :param signoff: The message to describe who locks the resource
        This method will lock the resource if it is requested.
            It will assign a new signoff message.

        :raises: AlreadyLockedException
        :returns: None
        """
        if self.can_lock:
            self.is_locked = True
            self.signoff = signoff
            self.save()
        else:
            raise AlreadyLockedException()

    def release(self):
        """
        Instance Method

        This method will release the resource if it is requested.
            Will reset the attribute if signoff to None.

        :raises: AlreadyFreeException
        :returns: None
        """
        if self.can_release:
            self.is_locked = False
            self.delete_signoff()
            self.delete_associated_queue()
            self.save()
        else:
            raise AlreadyFreeException()

    def delete_associated_queue(self):
        """
        Instance Method

        This method will set the associated_queue field to None
        :returns: None
        """
        self.associated_queue = None

    def delete_signoff(self):
        """
        Instance Method
        :returns: None
        """
        self.signoff = None

    def has_label(self, label):
        return label in self.labels

    def has_link(self):
        # Sometimes the link might be stringed none.
        # We want to ensure that it is not the case as well
        return self.link not in [None, "None"]

    def has_signoff(self):
        return self.signoff is not None

    @staticmethod
    def get_all_free_resources(ignore_maintenance=False):
        if ignore_maintenance:
            return LockableResource.objects.filter(is_locked=False)
        else:
            return LockableResource.objects.filter(
                is_locked=False, in_maintenance=False
            )

    def __str__(self):
        """
        Instance Magic Method __str__
        This will make the object more descriptive.
        Helpful in the Admin page
        """
        return self.name

    @staticmethod
    def get_all_labels():
        """
        Static Method
        Responsible to return a non-duplicated list of ALL the labels
            of the entire platform
        :return:
        """
        all_labels = []
        for lockable_resource in LockableResource.objects.all():
            for label in lockable_resource.labels:
                all_labels.append(label)

        # Lets remove duplicates by converting to a set:
        all_labels = set(all_labels)

        # Now revert this back to list:
        all_labels = list(all_labels)

        return all_labels

    def json_parse(self, **kwargs):
        """
        Instance Method
        Method prepares the object in parsed json.
        We want to omit several key values from the
        built-in __dict__ attribute, to have cleaner data
        Removals are in list: key_removals
        :return: JSON object
        """

lockable_resource/views.py
import lockable_resource.constants as const
import rqueue.constants as const_rqueue
from django.contrib import messages
from django.shortcuts import render, redirect, HttpResponse
from django.db.models import Q
from lockable_resource.models import *
from lockable_resource.query_param_manager import QueryParamManager
from lockable_resource.action_manager import LRActionObjectsHandler


def lockable_resources_page(request):
    if request.method == "GET":
        query_params = request.GET

        # Handle special query params first (like view_as=yaml)
        # These take precedence over status filtering
        for qp_key in QueryParamManager.SUPPORTED_QUERY_PARAMS:
            if qp_key in query_params:
                qp_val = query_params.get(qp_key)
                q_manager = QueryParamManager(qp_key, qp_val)
                data = q_manager.handle_key()
                if data is not None:
                    return HttpResponse(data, content_type="text/plain")

        # Get filter parameters
        status_filter = query_params.get("status", "all")
        provider_filter = query_params.get("provider", "")
        search_text = query_params.get("search", "")

        # Start with base queryset
        lockable_resources = LockableResource.objects.all()

        # Apply status filter
        if status_filter == "free":
            lockable_resources = lockable_resources.filter(
                is_locked=False, in_maintenance=False
            )
        elif status_filter == "locked":
            lockable_resources = lockable_resources.filter(is_locked=True)
        elif status_filter == "maintenance":
            lockable_resources = lockable_resources.filter(in_maintenance=True)
        else:
            status_filter = "all"

        # Apply provider filter
        if provider_filter:
            lockable_resources = lockable_resources.filter(provider=provider_filter)

        # Apply search filter across multiple fields
        if search_text:
            lockable_resources = lockable_resources.filter(
                Q(name__icontains=search_text)
                | Q(labels_string__icontains=search_text)
                | Q(signoff__icontains=search_text)
                | Q(description__icontains=search_text)
            )

        lockable_resources = lockable_resources.order_by("name")

        # Get all unique providers for the dropdown
        all_providers = (
            LockableResource.objects.values_list("provider", flat=True)
            .distinct()
            .order_by("provider")
        )

        return render(
            request,
            template_name="lockable_resource/all.html",
            context={
                "lockable_resources": lockable_resources,
                "status_filter": status_filter,
                "provider_filter": provider_filter,
                "search_text": search_text,
                "all_providers": all_providers,
                "show_filters": True,
            },
        )

    if request.method == "POST":
        # Get Desired Action:
        desired_action = request.POST.get("action")
        action_handler = LRActionObjectsHandler.SUPPORTED_ACTION_OBJECTS.get(
            desired_action
        )
        # Create an instance of the desired action handler
        action_obj = action_handler(request)
        action_obj.complete_action()

        return redirect("lockable_resources_page")


def lockable_resource_more_info(request, slug):
    lr = LockableResource.objects.get(id=slug)
    # Gather the next & previous Lockable resource and send as context
    # This is useful in this template only for navigating
    next_lr = lr.next_obj()
    previous_lr = lr.previous_obj()
    return render(
        request,
        template_name="lockable_resource/lockable_resource_more_info.html",
        context={
            "lockable_resource": lr,
            "next_lockable_resource": next_lr,
            "previous_lockable_resource": previous_lr,
        },
    )

templates/includes/action_queue_modal.html
<!--
    This template includes actions to do with the rqueues
    Supports: Abort
-->
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="Abort-Rqueue-{{ rqueue.id }}" class="modal fade">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
            <h4 class="modal-title">
                <b>Are you sure to abort {{ rqueue.id }} ?</b>
            </h4>
         </div>
         <div class="modal-body" style="">
            <h5>By clicking Confirm Abort, this queue will be in ABORTED state.</h5>
            <form class="form-inline" role="form" method="POST">
                {% csrf_token %}
                <br>
                <br>
                <br>
                <input type="hidden" id='rqueue_id' name="rqueue_id" value="{{ rqueue.id }}"/>
                <input type="hidden" id='action' name="action" value="aborted"/>
                <button type="submit" class="btn btn-success">
                   <i style="margin-right: 5px"></i>
                   <b>Confirm Abort</b>
                </button>
            </form>
         </div>
      </div>
   </div>
</div>

templates/includes/addon_lockable_resource_dropdown.html
<!-- This is the dropdown with the extended options -->
<!-- PLEASE DO NOT IMPORT MODAL FILES INSIDE <ul> TAGS, it does not function at all -->
{% for addon in installed_addons %}
    {% if addon == "expiry_addon" %}
        {% include "expiry_addon/modal.html" %}
    {% endif %}
{% endfor %}
<style>
    #addons a {
        color: white;
    }
    #addons a:hover, a:focus {
        color: black;
        background-color: white;
    }
</style>
<td>
    <div class="btn-group" id="addons">
        <button data-toggle="dropdown" class="btn btn-default dropdown-toggle" type="button" style="min-width: 105px">
                <span data-toggle="tooltip" data-placement="top" title="{{ lockable_resource.name }}">
                    <strong>Extended Options</strong>
                </span>
            <span class="caret"></span>
        </button>

        <ul class="dropdown-menu">
            {% for addon in installed_addons %}
                <!-- TODO: Find a better approach to differentiate what to display depending on which addon we iterate, avoid too much if's! -->
                {% if addon == "expiry_addon" %}
                    {% include "expiry_addon/dropdown.html" %}
                {% endif %}
            {% endfor %}
        </ul>

    </div>
    <div>
        {% for addon in installed_addons %}
            {% if addon == "expiry_addon" %}
                {% include "expiry_addon/info.html" %}
            {% endif %}
        {% endfor %}
    </div>
</td>

templates/includes/addon_status_table.html
<table class="table table-striped table-advance table-hover center-block" style="text-align: center">
  <tbody>
    <tr>
      <th style="text-align: center">
        <i class="icon_book"></i> ID
      </th>
      <th style="text-align: center">
        <i class="icon_loading"></i> Addon Package Name
      </th>
      <th style="text-align: center">
        <i class="icon_clock"></i> Actions
      </th>
    </tr>
    {% for addon in addons %}
      <tr>
        <td>{{ addon.id }}</td>
      <td>{{ addon.package_name }}</td>
      <td>
        <form class="form-inline" role="form" method="POST">
          {% csrf_token %}
          <input type="hidden" id='addon_application_name' name="addon_application_name" value="{{ addon.application_name }}"/>
          {% if addon.is_installed %}
            <input type="hidden" id="action" name="action" value="uninstall_addon">
            <button type="submit" class="btn btn-danger">
              <i style="margin-right: 5px" class="icon_cart"></i>
              <b>Uninstall Addon!</b>
            </button>
          {% else %}
            <input type="hidden" id="action" name="action" value="install_addon">
            <button type="submit" class="btn btn-success">
              <i style="margin-right: 5px" class="icon_cart"></i>
              <b>Install Addon!</b>
            </button>
          {% endif %}
        </form>
      </td>
    </tr> {% endfor %}
  </tbody>
</table>

templates/includes/change_priority_modals.html
{% for i in '1234'|make_list %}
<div aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1" id="Change-Priority-{{ i }}-{{ rqueue.id }}" class="modal fade">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
            <button aria-hidden="true" data-dismiss="modal" class="close" type="button">×</button>
            <h4 class="modal-title">
               <b>Change Priority for Pending request with ID: {{ rqueue.id }}</b>
            </h4>
         </div>
         <div class="modal-body" style="">
            <h5>
               By clicking Confirm, this pending request's priority will change to {{ i }}
            </h5>
            <form class="form-inline" role="form" method="POST">
               {% csrf_token %}
               <input type="hidden" id="action" name="action" value="change_priority">
               <input type="hidden" id='rqueue_id' name="rqueue_id" value="{{ rqueue.id }}"/>
               <input type="hidden" id='priority_value' name="priority_value" value="{{ i }}"/>

               <button type="submit" class="btn btn-large btn-danger">
                   <i style="margin-right: 5px"  class="arrow_up"></i>
                   Confirm Change of Priority to <b>{{ i }}</b>
               </button>
            </form>
         </div>
      </div>
   </div>
</div>
{% endfor %}

templates/includes/finished_requests_table.html
<div class="row">
  <div class="col-lg-12 justify-content-center">
    <section class="panel">
      <header class="panel-heading">
       Finished Requests
      </header>

      <table class="table table-striped table-advance table-hover center-block" style="text-align: center">
        <tbody>
          <tr>
            <th style="text-align: center"><i class="icon_loading"></i> ID</th>
            <th style="text-align: center"><i class="icon_clock"></i> Time Requested</th>
              <th style="text-align: center"><i class="arrow_up"></i> Priority Level</th>
            <th style="text-align: center"><i class="icon_datareport"></i> Options</th>
            <th style="text-align: center">
                <i class="icon_document"></i> Description
            </th>
            <th style="text-align: center">
                <i class="icon_pencil"></i> Name / Label
            </th>
            <th style="text-align: center">
                <i class="icon_pens"></i> Sign Off
            </th>
            <th style="text-align: center">
                <i class="icon_search"></i> Status
            </th>
            <th style="text-align: center"><i class="icon_clock"></i> Time Waited</th>
          </tr>
            {% for finishedqueue in finishedqueues %}
                <tr>
                    <td>
                        {{ finishedqueue.id }}
                    </td>
                    <td>
                        {{ finishedqueue.time_requested }}
                    </td>
                    <td>
                        {{ finishedqueue.priority }}
                    </td>
                    <td>
                        {% include 'includes/display_json_data_modal.html' %}
                        <div class="btn-group">
                            <a class="btn btn-info" href="{% url 'rqueue_more_info' finishedqueue.id %}">
                                <i class="icon_pencil"></i>
                                <span>Show Queue</span>
                            </a>
                            <a class="btn btn-info dropdown-toggle" data-toggle="dropdown" href="" title="Bootstrap 3 themes generator"><span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li>
                                    <a data-toggle="modal" href="#DisplayFinishedQueue-Data-{{ finishedqueue.id }}" title="See more info on this queue">
                                        Show JSON
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </td>
                    <!-- Row Description Start -->
                    <td>
                        <a data-original-title="Description for Rqueue with ID {{ finishedqueue.id }}"
                                data-content="{{ finishedqueue.description }}"
                                data-placement="right" data-trigger="hover"
                                class="btn btn-info popovers">
                            <i class="icon_document"></i>
                            <span></span> <!-- Could write some text here in the future if we want -->
                        </a>
                    </td>
                    <!-- Row Description End -->
                    <!-- Row Label Start -->
                    <td>
                        {{ finishedqueue.name }}
                        {{ finishedqueue.label }}
                        <!--{{ finishedqueue.labels_string }}-->
                    </td>
                    <!-- Row Label End -->
                    <!-- Row Signoff Start -->
                    <td>
                        {% if finishedqueue.link and finishedqueue.link != "None" %}
                            <a href="{{ finishedqueue.link }}">
                                {{ finishedqueue.signoff }}
                            </a>
                        {% else %}
                            {{ finishedqueue.signoff }}
                        {% endif %}
                    </td>
                    <!-- Row Signoff End -->
                    <td>
                        {{ finishedqueue.status }}
                    </td>
                    <td>
                        <span class="center-block" id="pended-time-{{ finishedqueue.id }}">
                            {{ finishedqueue.pended_time_descriptive }}
                        </span>
                        <div class="{{ finishedqueue.bootstrap_classes.loader }} pull-right"></div>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
      </table>
      <!-- Pagination Start -->
      <div class="text-center" style="background-color: #EEEEEE">
          <ul class="pagination pagination-lg">
            {% if finishedqueues.has_previous %}
                <li><a href="?page=1">&laquo; First</a></li>
                <li><a href="?page={{ finishedqueues.previous_page_number }}">Previous</a></li>
            {% endif %}
            {% for num in finishedqueues.paginator.page_range %}
                {% if finishedqueues.number == num %}
                    <li class="active"><a href="?page={{ num }}">{{ num }}</a></li>
                <!-- Otherwise, display 5 page options, it's not cool to display too much -->
                {% elif num > finishedqueues.number|add:'-5' and num < finishedqueues.number|add:'5' %}
                    <li><a href="?page={{ num }}">{{ num }}</a></li>
                {% endif %}
            {% endfor %}
            {% if finishedqueues.has_next %}
                <li><a href="?page={{ finishedqueues.next_page_number }}">Next</a></li>
                <li><a href="?page={{ finishedqueues.paginator.num_pages }}">Last &raquo;</a></li>
            {% endif %}
          </ul>
      </div>
      <!-- Pagination End -->
    </section>
  </div>
</div>

templates/includes/my_locked_resources.html
{% if user_locked_resources %}
    {% include 'includes/lockable_resource_table.html' with lockable_resources=user_locked_resources %}
{% else %}
    <div class="row">
        <div class="col-lg-12">
            <div class="alert alert-info fade in">
                <button data-dismiss="alert" class="ml-2 mb-1 close" type="button">
                    <span aria-hidden="true"></span>
                </button>
                <strong>
                    Great! You don't have any locked resources
                </strong>
            </div>
        </div>
    </div>
{% endif %}

templates/includes/sidebar.html
<aside>
   <div id="sidebar" class="nav-collapse">
      <!-- sidebar menu start-->
      <ul class="sidebar-menu">
         <li class="active">
            <a href="{% url 'dashboard_page' %}">
            <i class="icon_datareport"></i>
            <span>Dashboard</span>
            </a>
         </li>
         <li>
            <a href="{% url 'lockable_resources_page' %}">
            <i class="icon_house_alt"></i>
            <span>Lockable Resources</span>
            </a>
         </li>
         <li>
            <a href="{% url 'pending_requests_page' %}">
            <i class="icon_loading"></i>
            <span>Pending Requests</span>
            </a>
         </li>
         <li>
            <a href="{% url 'finished_requests_page' %}">
            <i class="icon_check"></i>
            <span>Finished Requests</span>
            </a>
         </li>
         <li>
            <a href="https://github.com/jimdevops19/rlocker/">
            <i class="icon_document"></i>
            <span>Documentation</span>
            </a>
         </li>
         {% if user.is_staff %}
             <li>
                <a style="color: #fabb3d" href="{% url 'admin:index' %}">
                <i class="icon_error-triangle"></i>
                <span>Admin Page</span>
                </a>
            </li>
             <li>
                <a style="color: #fabb3d" href="{% url 'admin_tools:index' %}">
                <i class="icon_error-triangle"></i>
                <span>Administrative Tools</span>
                </a>
            </li>
         {% endif %}
      </ul>
      <!-- sidebar menu end-->
   </div>
</aside>

templates/includes/toolbox.html
<a href="{{ tool.url }}">
    <div class="col-lg-6">
        <div class="social-box twitter">
            <i class="fa fa-arrow-right"></i>
            <span style="font-size: 32px; color: gray">
                {{ tool.name }}
            </span>
        </div>
    </div>
</a>